<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>9.0</LangVersion>
    <DefineConstants>UNITY_EDITOR;UNITY_EDITOR_WIN;ENABLE_INPUT_SYSTEM</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Runtime/**/*.cs" />
    <Compile Include="Editor/**/*.cs" />
    <Compile Include="Samples~/**/*.cs" />
  </ItemGroup>
</Project>
